# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bbbc26ef00cfaac43f5d03a71454911ad30587fd97da61b4c29e55f3f22ac64c60bd2ff627174abdba011c0b7a9ed6a1fa408ac7a164fcf9a57d62af8a6c3fe

test:
  secret_key_base: a2936693cedfd60bfc3cc8f0451d6795b77fe34a32ac9d28c373d860e058af99e697f6f04813c0415bb1667ee9b7b018aa0a0bc837349e2cf689f85c763b5911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
